#! /bin/sh

# QUICKSTART INSTALL
# ==================
#
# This is a quick guide to building and installing.
#
# Assumes install in ~/reorder.
#
# See README for installing required 32-bit packages.
#
# Quickstart install - in ~/reorder
# =================================

# make reorder dir

  mkdir ~/reorder
  cd ~/reorder

# clone the git repositories

  git clone https://github.com/ncar/lrose-netcdf
  git clone https://github.com/ncar/lrose-reorder

# build and install netcdf into ~/reorder

  cd ~/reorder/lrose-netcdf/
  ./build_and_install_netcdf.m32 -x ~/reorder/

# build and install reorder binaries

  cd ~/reorder/lrose-reorder
  ./configure --prefix=${HOME}/reorder
  make install

# =================================
# Binaries will be in:
#
#  ~/reorder/bin




